[project]
name = "thingsboard-mcp-server"
version = "0.1.0"
description = "MCP server for ThingsBoard API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "fastmcp>=2.11.2"
]
